spring:
  application:
    name: uberlocationservice
server:
  port: 7778

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    prefer-ip-address: true






#spring.data.redis.host=localhost
#spring.data.redis.port=6379